### ISSUE TITLE
2.3.0 TODO

### ISSUE THREAD

**Issue by tterrag1098** [TheCricket/Chisel-2#117]
- [x] Finish chisel modes
- [x] Finish AutoChisel animation/sound
- [x] Finish Arcane and Futura Blocks
- [x] Prototype Antiblocks
- [x] Create new Chisel GUI that would help efforts to unify some block groups and remove 24 block-limit for display
- [x] Unify Blockgroups (Fantasy + Fantasy2, Technical+Technical2+Factory, SmoothStone+StoneBricks)

**Comment by Drullkus** [comment]
TODO
Finish Arcane and Futura Blocks
Create new Chisel GUI that would help efforts to unify some blockgroups and remove 24-block-limit for display

**Comment by Drullkus** [comment]
What I'm thinking is that we can restructure how some blockgroups are grouped and maybe even unify some groups.

Ideas of unification
- Unify Technical Blocks, Technical2 Blocks, Factory Blocks, and Futura blocks
- Unify Stone blocks (Smooth stone) and Stone Bricks

**Comment by Drullkus** [comment]
With a revamped GUI we can access all of these blocks. Probably. :P

**Comment by TheCricket** [comment]
Maybe like a scrolling thing

**Comment by Drullkus** [comment]
Either a scrollable list or a search field

Or both

**Comment by tterrag1098** [comment]
Removed your first comment and added it to the OP. You could have done that btw ;P

**Comment by Drullkus** [comment]
Done: Expanded Chisel GUI

**Comment by warlordjones** [comment]
With the unification, are we going to keep the ability to craft the base factory block, the base futura block etc, even if they can be chiseled into each other?

Additionally, Fantasy and Fantasy2 could be unified.

**Comment by tterrag1098** [comment]
The unification will be much easier now with the loss of the 24 block limit and the registry refactor.

**Comment by erkro1** [comment]
So is there any ETA for 2.3.0? Is it like days, weeks or months away, or is it hard to say?

**Comment by tterrag1098** [comment]
Hopefully days. We are pretty close.

**Comment by CptSpaceToaster** [comment]
Unless the two checkboxes were finished, but not recorded, this issue isn't done yet.

**Comment by tterrag1098** [comment]
@CptSpaceToaster We decided against unifying those groups, and I believe the overlay for futura was finished.

**Comment by CptSpaceToaster** [comment]
no problem, I just didn't want this one to slip through the cracks.

**Comment by tterrag1098** [comment]
All checked, happy? :P

**Comment by Drullkus** [comment]
Why did we not unify those block groups? :(
